name: build

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout Project
        uses: actions/checkout@v2
      - name: add tools
        run: brew bundle
      - name: build
        run: xcodebuild clean build -configuration Release
      - name: Stage Artifact
        run: mkdir bundle && cp -r build/Release/Polyhedra.saver bundle/
      - name: 'Store Artifact'
        uses: actions/upload-artifact@v2
        with:
          name: Polyhedra.saver
          path: bundle/