name: build

on:
  push:
    tags:
      - 'v*'
    branches:
      - master
      - develop
  pull_request:
    branches:
      - master
      - develop

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout Project
        uses: actions/checkout@v3
      - name: Get the configuration
        id: get_configuration
        run: |
          [ $(echo ${{ github.ref }} | cut -d / -f 2) = "tags" ] && echo ::set-output name=configuration::Release || echo ::set-output name=configuration::Debug
      - name: build
        run: xcodebuild clean build -configuration ${{ steps.get_configuration.outputs.configuration }}
      - name: Stage Artifact
        run: mkdir bundle && cp -r build/${{ steps.get_configuration.outputs.configuration }}/Polyhedra.saver bundle/
      - name: 'Store Artifact'
        uses: actions/upload-artifact@v3
        with:
          name: Polyhedra.saver
          path: bundle/